In [1]:
import numpy as np
import pandas as pd
import plotly
import plotly.figure_factory as ff
import plotly.graph_objs as go
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [2]:
data = pd.read_csv('task_b.csv')
data=data.iloc[:,1:]

In [3]:
data.head()

f1            f2        f3    y
0  -195.871045 -14843.084171  5.532140  1.0
1 -1217.183964  -4068.124621  4.416082  1.0
2     9.138451   4413.412028  0.425317  0.0
3   363.824242  15474.760647  1.094119  0.0
4  -768.812047  -7963.932192  1.870536  0.0

In [4]:
data.corr()['y']

f1    0.067172
f2   -0.017944
f3    0.839060
y     1.000000
Name: y, dtype: float64

In [5]:
data.std()

f1      488.195035
f2    10403.417325
f3        2.926662
y         0.501255
dtype: float64

In [6]:
X=data[['f1','f2','f3']].values
Y=data['y'].values
print(X.shape)
print(Y.shape)

(200, 3)
(200,)


# What if our features are with different variance 

<pre>
* <b>As part of this task you will observe how linear models work in case of data having feautres with different variance</b>
* <b>from the output of the above cells you can observe that var(F2)>>var(F1)>>Var(F3)</b>

> <b>Task1</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' and check the feature importance

> <b>Task2</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance

</pre>

<h3><font color='blue'> Make sure you write the observations for each task, why a particular feautre got more importance than others</font></h3>

In [7]:
columns = ['f1', 'f2', 'f3', 'y']
features = data.columns.drop("y").values
features

array(['f1', 'f2', 'f3'], dtype=object)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier


clf_lr = SGDClassifier(loss ="log",random_state = 32)
clf_lr.fit(X,Y)

feature_importance = abs(clf_lr.coef_[0])
feature_importance

array([ 4283.68856793,  2171.43530166, 10226.43581458])

In [9]:
feature_importance_lr = np.argsort(feature_importance)[::-1]
feature_importance_lr

array([2, 0, 1], dtype=int64)

In [10]:
features

array(['f1', 'f2', 'f3'], dtype=object)

In [11]:
for i in feature_importance_lr:
    print(features[i], feature_importance[i])

f3 10226.435814582052
f1 4283.688567931984
f2 2171.435301659141


In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier


clf_svm = SGDClassifier(random_state = 32)
clf_svm.fit(X,Y)

feature_importance = abs(clf_svm.coef_[0])
feature_importance

array([ 6961.34278305,  2756.13532078, 10055.59408444])

In [13]:
feature_importance_svm = np.argsort(feature_importance)[::-1]
feature_importance_svm

array([2, 0, 1], dtype=int64)

In [14]:
features

array(['f1', 'f2', 'f3'], dtype=object)

In [15]:
for i in feature_importance_svm:
    print(features[i], feature_importance[i])

f3 10055.594084443455
f1 6961.342783053188
f2 2756.1353207829634


# TASK 2

In [16]:
scaling = StandardScaler()
X_s = scaling.fit_transform(data[['f1', 'f2', 'f3']])

In [17]:
clf_lr = SGDClassifier(loss ="log",random_state = 10)
clf_lr.fit(X_s,Y)

feature_importance = abs(clf_lr.coef_[0])
feature_importance

array([1.27790049, 0.28064243, 8.91691905])

In [18]:
feature_importance_std_lr = np.argsort(feature_importance)[::-1]
feature_importance_std_lr

array([2, 0, 1], dtype=int64)

In [19]:
features

array(['f1', 'f2', 'f3'], dtype=object)

In [20]:
for i in feature_importance_std_lr:
    print(features[i], feature_importance[i])

f3 8.91691904994988
f1 1.2779004904317495
f2 0.2806424259073557


In [21]:
clf_svm = SGDClassifier(random_state = 10)
clf_svm.fit(X_s,Y)

feature_importance = abs(clf_svm.coef_[0])
feature_importance

array([ 2.690998  ,  2.03354351, 24.59605568])

In [22]:
feature_importance_std_svm = np.argsort(feature_importance)[::-1]
feature_importance_std_svm

array([2, 0, 1], dtype=int64)

In [23]:
features

array(['f1', 'f2', 'f3'], dtype=object)

In [24]:
for i in feature_importance_std_svm:
    print(features[i], feature_importance[i])

f3 24.596055681348748
f1 2.6909979968437283
f2 2.033543514674772


### Observations:

How "important" a feature is only makes sense in the context of a specific model being used and not in real world.
"Important" in feature importance is realtive.
Variance is the measurement of the spread between numbers in a variable. 
It measures how far a number is from the mean and every number in a variable.
The variance of a feature determines how much it is impacting the response variable. 
If the variance is low, it implies there is no impact of this feature on response and vice-versa.
Features with higher coeffiecient means they are more important.
Standardization do not add information, difficult to interpret and at times seriously misleading information.
Here we observe consistantly that F3 has the highest Feature Importance as it has the highest correlation, variance and coeffiecient and lowest standard deviation.