<h1><font color='blue'> 8E and 8F: Finding the Probability P(Y==1|X)</font></h1>

<h2><font color='Geen'> 8E: Implementing Decision Function of SVM RBF Kernel</font></h2>

<font face=' Comic Sans MS' size=3>After we train a kernel SVM model, we will be getting support vectors and their corresponsing coefficients $\alpha_{i}$

Check the documentation for better understanding of these attributes: 

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
<img src='https://i.imgur.com/K11msU4.png' width=500>

As a part of this assignment you will be implementing the ```decision_function()``` of kernel SVM, here decision_function() means based on the value return by ```decision_function()``` model will classify the data point either as positive or negative

Ex 1: In logistic regression After traning the models with the optimal weights $w$ we get, we will find the value $\frac{1}{1+\exp(-(wx+b))}$, if this value comes out to be < 0.5 we will mark it as negative class, else its positive class

Ex 2: In Linear SVM After traning the models with the optimal weights $w$ we get, we will find the value of $sign(wx+b)$, if this value comes out to be -ve we will mark it as negative class, else its positive class.

Similarly in Kernel SVM After traning the models with the coefficients $\alpha_{i}$ we get, we will find the value of 
$sign(\sum_{i=1}^{n}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here $K(x_{i},x_{q})$ is the RBF kernel. If this value comes out to be -ve we will mark $x_{q}$ as negative class, else its positive class.

RBF kernel is defined as: $K(x_{i},x_{q})$ = $exp(-\gamma ||x_{i} - x_{q}||^2)$

For better understanding check this link: https://scikit-learn.org/stable/modules/svm.html#svm-mathematical-formulation
</font>

## Task E

> 1. Split the data into $X_{train}$(60), $X_{cv}$(20), $X_{test}$(20)

> 2. Train $SVC(gamma=0.001, C=100.)$ on the ($X_{train}$, $y_{train}$)

> 3. Get the decision boundry values $f_{cv}$ on the $X_{cv}$ data  i.e. ` `$f_{cv}$ ```= decision_function(```$X_{cv}$```)```  <font color='red'>you need to implement this decision_function()</font>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
import numpy as np
from sklearn.svm import SVC

In [2]:
X, y = make_classification(n_samples=5000, n_features=5, n_redundant=2,
                           n_classes=2, weights=[0.7], class_sep=0.7, random_state=15)

### Pseudo code

clf = SVC(gamma=0.001, C=100.)<br>
clf.fit(Xtrain, ytrain)

<font color='green'>def</font> <font color='blue'>decision_function</font>(Xcv, ...): #use appropriate parameters <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>for</font> a data point $x_q$ <font color='green'>in</font> Xcv: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='grey'>#write code to implement $(\sum_{i=1}^{\text{all the support vectors}}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here the values $y_i$, $\alpha_{i}$, and $intercept$ can be obtained from the trained model</font><br>
   <font color='green'>return</font> <font color='grey'><i># the decision_function output for all the data points in the Xcv</i></font>
    
fcv = decision_function(Xcv, ...)  <i># based on your requirement you can pass any other parameters </i>

<b>Note</b>: Make sure the values you get as fcv, should be equal to outputs of clf.decision_function(Xcv)


In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
X_train, X_cv, y_train, y_cv = train_test_split(X_train, y_train, test_size=0.25, stratify=y_train, random_state=42)

In [4]:
gamma = 0.001
C = 100
clf = SVC(kernel = 'rbf', gamma = gamma, C = C)
clf.fit(X_train, y_train)

def rbf(sv , xq , gamma):
    norm = np.linalg.norm(sv-xq)
    return  np.exp(-gamma *(norm**2))

def decision_function(X_cv , gamma , support_vectors ,dual_coef , intercept):
    decision_vector = []
    for xq in X_cv :
        dec_func = 0
        for sv , dc  in zip(support_vectors , dual_coef[0] ):
            dec_func += (dc * rbf(sv,xq, gamma))
        dec_func += intercept[0]
        decision_vector.append(dec_func)
    return decision_vector

support_vectors = clf.support_vectors_
dual_coef = clf.dual_coef_
intercept = clf.intercept_
f_cv = decision_function(X_cv , gamma , support_vectors ,dual_coef , intercept)
f_cv

# https://stackoverflow.com/questions/28503932/calculating-decision-function-of-svm-manually

[2.15710055245017,
 0.018191354992135977,
 -2.7098855187549633,
 -0.42379764164899303,
 2.8158409646208,
 -1.8304835921470657,
 1.5274543025698746,
 -1.47130174079732,
 2.357663624311196,
 2.866437393538912,
 0.467893288325139,
 -1.3345726264108935,
 2.639385939740431,
 -1.6411954391593655,
 1.656150591623553,
 -0.5538503546250739,
 -3.307964485214147,
 1.6988353830288174,
 -0.9005781751963484,
 -3.2225155772119267,
 -3.481789161097372,
 -3.3167598453990808,
 -1.9624301914942537,
 1.9377403436731653,
 1.549969083403492,
 0.27771548055549555,
 -3.0986480124180718,
 -2.0057334847859964,
 0.8363772523107071,
 -2.5082451388521934,
 -3.7533618693353974,
 -3.802107220141669,
 1.7635396164912391,
 0.2960823476611081,
 -0.1856963139976857,
 -2.2699544057405108,
 -3.561843544327833,
 1.8071136552070994,
 3.0815363620292215,
 0.5888576761404165,
 0.9070744146660514,
 1.7382542906258847,
 -2.7209997650640263,
 -3.9322614063883963,
 -2.7020980882048677,
 -0.38565232756751744,
 -0.7466061884580784,

In [5]:
clf.decision_function(X_cv)

array([ 2.15710055e+00,  1.81913550e-02, -2.70988552e+00, -4.23797642e-01,
        2.81584096e+00, -1.83048359e+00,  1.52745430e+00, -1.47130174e+00,
        2.35766362e+00,  2.86643739e+00,  4.67893288e-01, -1.33457263e+00,
        2.63938594e+00, -1.64119544e+00,  1.65615059e+00, -5.53850355e-01,
       -3.30796449e+00,  1.69883538e+00, -9.00578175e-01, -3.22251558e+00,
       -3.48178916e+00, -3.31675985e+00, -1.96243019e+00,  1.93774034e+00,
        1.54996908e+00,  2.77715481e-01, -3.09864801e+00, -2.00573348e+00,
        8.36377252e-01, -2.50824514e+00, -3.75336187e+00, -3.80210722e+00,
        1.76353962e+00,  2.96082348e-01, -1.85696314e-01, -2.26995441e+00,
       -3.56184354e+00,  1.80711366e+00,  3.08153636e+00,  5.88857676e-01,
        9.07074415e-01,  1.73825429e+00, -2.72099977e+00, -3.93226141e+00,
       -2.70209809e+00, -3.85652328e-01, -7.46606188e-01, -6.82441191e-01,
        7.32442689e-01, -3.46515359e+00, -1.61115744e+00,  1.65655229e+00,
       -2.83622683e+00, -

<h2><font color='Geen'> 8F: Implementing Platt Scaling to find P(Y==1|X)</font></h2>

Check this <a href='https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a'>PDF</a>
<img src='https://i.imgur.com/CAMnVnh.png'>


## TASK F


> 4. Apply SGD algorithm with ($f_{cv}$, $y_{cv}$) and find the weight $W$ intercept $b$ ```Note: here our data is of one dimensional so we will have a one dimensional weight vector i.e W.shape (1,)``` 

> Note1: Don't forget to change the values of $y_{cv}$ as mentioned in the above image. you will calculate y+, y- based on data points in train data

> Note2: the Sklearn's SGD algorithm doesn't support the real valued outputs, you need to use the code that was done in the `'Logistic Regression with SGD and L2'` Assignment after modifying loss function, and use same parameters that used in that assignment.
<img src='https://i.imgur.com/zKYE9Oc.png'>
if Y[i] is 1, it will be replaced with y+ value else it will replaced with y- value

> 5. For a given data point from $X_{test}$, $P(Y=1|X) = \frac{1}{1+exp(-(W*f_{test}+ b))}$ where ` `$f_{test}$ ```= decision_function(```$X_{test}$```)```, W and b will be learned as metioned in the above step

In [6]:
from sklearn.linear_model import SGDClassifier

In [7]:
N_pos = []
N_neg = []
for i in y_train:
    if i == 1:
        N_pos.append(i)
    else:
        N_neg.append(i)
N_pos = len(N_pos)
N_neg = len(N_neg)
N_pos, N_neg

(908, 2092)

In [8]:
y_pos = (N_pos + 1)/ (N_pos + 2)
y_pos

0.9989010989010989

In [9]:
y_neg = 1 / (N_neg + 2)
y_neg

0.0004775549188156638

In [10]:
new_y_cv = []
for j in y_cv:
    if j != 1:
        new_y_cv.append(y_neg)
    elif j == 1:
        new_y_cv.append(y_pos)
new_y_cv

[0.9989010989010989,
 0.9989010989010989,
 0.0004775549188156638,
 0.0004775549188156638,
 0.9989010989010989,
 0.0004775549188156638,
 0.9989010989010989,
 0.0004775549188156638,
 0.9989010989010989,
 0.9989010989010989,
 0.9989010989010989,
 0.0004775549188156638,
 0.9989010989010989,
 0.0004775549188156638,
 0.9989010989010989,
 0.0004775549188156638,
 0.0004775549188156638,
 0.9989010989010989,
 0.0004775549188156638,
 0.0004775549188156638,
 0.0004775549188156638,
 0.0004775549188156638,
 0.0004775549188156638,
 0.9989010989010989,
 0.9989010989010989,
 0.9989010989010989,
 0.0004775549188156638,
 0.0004775549188156638,
 0.9989010989010989,
 0.9989010989010989,
 0.0004775549188156638,
 0.0004775549188156638,
 0.9989010989010989,
 0.0004775549188156638,
 0.0004775549188156638,
 0.0004775549188156638,
 0.0004775549188156638,
 0.9989010989010989,
 0.9989010989010989,
 0.9989010989010989,
 0.9989010989010989,
 0.9989010989010989,
 0.0004775549188156638,
 0.0004775549188156638,
 0.0004

In [11]:
%%time
from tqdm import tqdm
import math
from math import log

def initialize_weights(dim):
    dim = X_train[0] 
    w = np.zeros((1,))
    b = 0
   
    return w,b

dim = X_train[0] 
w,b = initialize_weights(dim)


def sigmoid(z):

    return 1. / (1 + np. exp(-z))

def logloss(y_true,y_pred):
    
    loss = -sum(map(lambda y_true, y_pred: y_true*np.log10(y_pred) + (1-y_true)*np.log10(1-y_pred), y_true, y_pred))/len(y_true)

    return loss

def gradient_dw(x,y,w,b,alpha,N):

    dw = x * (y - sigmoid(np.dot(w, x) + b)) - (alpha / N) * w

    return dw

def gradient_db(x,y,w,b):
    
    db = y - sigmoid(np.dot(w, x) + b)

    return db

log_loss=[]
epoch_list = []
def train(X_train,y_train):

    w,b = initialize_weights(X_train[0])
    eta0 = 0.0001
    
    for e in tqdm(range(epochs)):
        y_tr_pred=[]
        y_ts_pred=[]
        for i in range(len(X_train)):
            
            w = w + (eta0 * gradient_dw(X_train[i], y_train[i], w, b, alpha, N))
            b = b + (eta0 * gradient_db(X_train[i], y_train[i], w, b))

        for k in range(len(X_train)):
            z = np.dot(w,X_train[k])+b
            s = sigmoid(z)
            y_tr_pred.append(s)
        l_tr = logloss(y_train,y_tr_pred)
        log_loss.append(l_tr)


        epoch_list.append(e)
        
    return w,b

Wall time: 15.1 ms


In [12]:
%%time
alpha=0.0001
eta0=0.0001
N=len(f_cv)
epochs=50
w,b=train(f_cv,new_y_cv)

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00, 11.33it/s]

Wall time: 4.43 s


In [13]:
w

array([1.2115534])

In [14]:
b

array([-0.1914117])

In [15]:
f_test = clf.decision_function(X_test)
f_test

array([-2.75659154e+00,  1.78943826e+00, -3.24944981e+00, -1.13911207e+00,
       -3.45830871e+00, -3.08373912e+00, -3.40550511e+00, -2.48539247e+00,
       -2.86898419e+00, -1.99123102e+00,  7.99152093e-01, -5.53811580e-01,
        8.50417960e-01,  1.78046096e+00, -1.82684121e+00, -3.01322669e+00,
        1.76776596e+00,  5.54363971e-01, -2.21256913e+00, -1.10422726e+00,
       -2.69823995e+00, -3.45630605e+00,  1.53177465e+00, -2.64505747e+00,
       -1.04687770e-01, -3.53198921e+00,  6.15870926e-01, -3.06163288e+00,
        1.39224337e+00,  1.09821437e+00, -3.66935602e+00,  3.47530106e-01,
       -3.94784202e+00, -2.94205621e+00, -3.40533273e+00, -3.51136246e+00,
       -2.04856502e+00,  1.16851377e+00,  1.63078358e+00, -3.39924921e+00,
       -2.25602481e+00, -3.24608817e+00, -3.11238869e+00,  5.62755013e-01,
       -3.16104995e+00, -2.07913205e+00, -1.27715235e+00, -2.37290670e+00,
       -6.48402618e-01, -3.56970763e-01, -1.00686241e+00, -2.64076478e+00,
       -2.17978635e-01, -

In [16]:
p = 1 / 1 + np.exp(-((w*f_test)+b))
p

array([3.51639013e+01, 1.13854109e+00, 6.30719177e+01, 5.81389634e+00,
       8.09448795e+01, 5.17812060e+01, 7.59906180e+01, 2.55963340e+01,
       4.01476058e+01, 1.45162737e+01, 1.45987354e+00, 3.36880121e+00,
       1.43217915e+00, 1.14005615e+00, 1.20754105e+01, 4.76231292e+01,
       1.14222696e+00, 1.61864118e+00, 1.86733414e+01, 5.61467755e+00,
       3.28320453e+01, 8.07511414e+01, 1.18930135e+00, 3.08456791e+01,
       2.37471513e+00, 8.84096116e+01, 1.57421648e+00, 5.04391903e+01,
       1.22416666e+00, 1.32009622e+00, 1.04237533e+02, 1.79482002e+00,
       1.45666796e+02, 4.37714111e+01, 7.59749578e+01, 8.62522780e+01,
       1.54885347e+01, 1.29396190e+00, 1.16790286e+00, 7.54243856e+01,
       1.96287529e+01, 6.28196247e+01, 5.35747941e+01, 1.61238381e+00,
       5.67675704e+01, 1.60351563e+01, 6.69022605e+00, 2.24626645e+01,
       3.65643793e+00, 2.86619360e+00, 5.10119862e+00, 3.06908601e+01,
       2.57696870e+00, 8.50993279e+01, 1.41437161e+01, 9.60641425e+00,
      

__Note: in the above algorithm, the steps 2, 4 might need hyper parameter tuning, To reduce the complexity of the assignment we are excluding the hyerparameter tuning part, but intrested students can try that__


If any one wants to try other calibration algorithm istonic regression also please check these tutorials

1. http://fa.bianp.net/blog/tag/scikit-learn.html#fn:1

2. https://drive.google.com/open?id=1MzmA7QaP58RDzocB0RBmRiWfl7Co_VJ7

3. https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a

4. https://stat.fandom.com/wiki/Isotonic_regression#Pool_Adjacent_Violators_Algorithm
